#!/usr/bin/awk -f
#
# Copyright (C) 2018 Tai Chi Minh Ralph Eastwood <tcmreastwood@gmail.com> 
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

BEGIN {
	if (!fn) fn = "convert"
	if (!fin) intype = 1
	if (!fout) outtype = 2
	if (!intype) intype = "int"
	if (!outtype) outtype = "int"
	if (!errcode) errcode = "-1"
	if (!headers) headers = ""

	hs = split(headers, ha, ";")
	print "/* See LICENSE file for copyright and license details."
	print " * Generated by mkswitch.awk"
	print " */"
	if (hs > 0) {
		print
		print "/* headers included using headers= parameter */"
	}
	for (h in ha) {
		print "#include " ha[h]
	}
	print
	print outtype
	print fn "(" intype " value)"
	print "{"
}

{
	if (out[$fout] == "") {
		out[$fout] = $fin
	} else {
		out[$fout] = out[$fout] ";" $fin
	}
}

END {
	print "\tswitch (value) {"
	for (i in out) {
		os = split(out[i], oa, ";")
		for (o in oa) print "\tcase " oa[o] ":"
		print "\t\treturn " i ";"
	}
	print "\tdefault: return " errcode ";"
	print "\t}"
	print "}"
}
